import { chromium } from 'playwright';
import fs from 'node:fs';
const env = Object.fromEntries(fs.readFileSync(new URL('../.env.local', import.meta.url), 'utf8').split('\n').filter(l => l && !l.startsWith('#') && l.includes('=')).map(l => { const i = l.indexOf('='); return [l.slice(0, i).trim(), l.slice(i + 1).trim()]; }));
const SR = env.SUPABASE_SERVICE_ROLE_KEY, BASE = env.NEXT_PUBLIC_SUPABASE_URL, APP = 'http://localhost:3000';
const H = { apikey: SR, Authorization: `Bearer ${SR}` };
const DIR = '/tmp/wl_demo'; fs.mkdirSync(DIR, { recursive: true });
const demo = (await (await fetch(`${BASE}/rest/v1/users?email=eq.demo@cubes.test&select=id,active_team`, { headers: H })).json())[0];
const projs = await (await fetch(`${BASE}/rest/v1/projects?team_id=eq.${demo.active_team}&select=id,name&order=created_at&limit=1`, { headers: H })).json();
const pid = projs[0].id;
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto(`${APP}/login`, { waitUntil: 'networkidle' });
await page.locator('input#email, input[type="email"]').first().fill('demo@cubes.test');
await page.locator('input#password, input[type="password"]').first().fill('Demo1234!');
await page.getByRole('button', { name: /sign in|log ?in/i }).first().click();
await page.waitForURL('**/home', { timeout: 20000 }).catch(() => {});
const shot = async (n, url) => { await page.goto(`${APP}${url}`, { waitUntil: 'networkidle' }); await page.waitForTimeout(3000); await page.screenshot({ path: `${DIR}/${n}.png` }); console.log('shot', n); };
await shot('home', '/home');
await shot('projects', '/projects');
await shot('board', `/projects/${pid}?tab=board`);
await shot('tasks', `/projects/${pid}?tab=tasks`);
await shot('reporting', '/reporting/projects');
await browser.close();
console.log('done; project', pid);
